### ISSUE TITLE
--no-stream flag broken

### ISSUE THREAD

**Issue by perkel666** [kwaroran/RisuAI#79]
## HOW TO REPLICATE

check --no-stream or add it as a flag to webui.py --> CMD_FLAGS = --no-stream

this is vanilla latest version clean install

## Traceback:

```
Traceback (most recent call last):
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 1046, in <module>
    create_interface()
  File "C:\AI\oobabooga_windows\text-generation-webui\server.py", line 957, in create_interface
    shared.gradio['interface'].launch(prevent_thread_lock=True, share=shared.args.share, server_port=shared.args.listen_port, inbrowser=shared.args.auto_launch, auth=auth)
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1727, in launch
    self.validate_queue_settings()
  File "C:\AI\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1575, in validate_queue_settings
    raise ValueError(
ValueError: Queue needs to be enabled! You may get this error by either 1) passing a function that uses the yield keyword into an interface without enabling the queue or 2) defining an event that cancels another event without enabling the queue. Both can be solved by calling .queue() before .launch()
```

**Comment by perkel666** [comment]
wrong git sorry
